version: "3.9"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - LLM_PROVIDER=${LLM_PROVIDER:-openai}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://host.docker.internal:11434}
      - OLLAMA_MODEL=${OLLAMA_MODEL:-llama3.1:8b}
      - TRANSFORMERS_MODEL=${TRANSFORMERS_MODEL:-mistralai/Mistral-7B-Instruct-v0.2}

  ui:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - .:/app
    command: bash -lc "pip install --no-cache-dir -r requirements.txt && streamlit run src/ui/app.py --server.port 8501 --server.address 0.0.0.0"
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api

